SELECT PAYMENT.* FROM PAYMENT JOIN PAYMENTTYPE PT on PT.ID = PAYMENT.TYPE_ID WHERE PT.NAME = 'MONTHLY';
SELECT * FROM MARK WHERE SUBJECT_ID IN (SELECT ID FROM SUBJECT WHERE NAME = 'Art');
SELECT DISTINCT STUDENT.* FROM STUDENT JOIN PAYMENT P ON STUDENT.ID = P.STUDENT_ID JOIN PAYMENTTYPE PT ON PT.ID = P.TYPE_ID WHERE PT.NAME = 'WEEKLY';
SELECT STUDENT.* FROM STUDENT JOIN MARK M on STUDENT.ID = M.STUDENT_ID JOIN SUBJECT S on M.SUBJECT_ID = S.ID WHERE S.NAME = 'Math';