DELETE FROM STUDENT WHERE ID IN (SELECT DISTINCT STUDENT_ID FROM MARK JOIN SUBJECT S on S.ID = MARK.SUBJECT_ID WHERE S.GRADE >= 4);
DELETE FROM STUDENT WHERE ID IN (SELECT STUDENT_ID FROM MARK GROUP BY STUDENT_ID HAVING MIN(MARK) < 4);
DELETE FROM PAYMENTTYPE WHERE NAME = 'DAILY';
DELETE FROM MARK WHERE MARK < 7;