SELECT * FROM MARK WHERE MARK > 6 ORDER BY MARK DESC;
SELECT * FROM PAYMENT WHERE AMOUNT < 300 ORDER BY AMOUNT;
SELECT * FROM PAYMENTTYPE ORDER BY NAME;
SELECT * FROM STUDENT ORDER BY NAME DESC;
SELECT * FROM STUDENT WHERE ID IN (SELECT STUDENT_ID FROM PAYMENT WHERE AMOUNT > 1000) ORDER BY BIRTHDAY;