ALTER TABLE STUDENT ALTER COLUMN BIRTHDAY SET NOT NULL;
ALTER TABLE MARK ADD CHECK (MARK BETWEEN 1 AND 10);
ALTER TABLE MARK ALTER COLUMN STUDENT_ID SET NOT NULL;
ALTER TABLE MARK ALTER COLUMN SUBJECT_ID SET NOT NULL;
ALTER TABLE SUBJECT ADD CHECK (GRADE BETWEEN 1 AND 5);
ALTER TABLE PAYMENTTYPE ADD UNIQUE (NAME);
ALTER TABLE PAYMENT ALTER COLUMN TYPE_ID SET NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN AMOUNT SET NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN PAYMENT_DATE SET NOT NULL;