SELECT MAX(BIRTHDAY) FROM STUDENT;
SELECT MIN(PAYMENT_DATE) FROM PAYMENT;
SELECT AVG(MARK) FROM MARK JOIN SUBJECT S ON S.ID = MARK.SUBJECT_ID WHERE S.NAME = 'Math';
SELECT MIN(AMOUNT) FROM PAYMENT JOIN PAYMENTTYPE PT on PT.ID = PAYMENT.TYPE_ID WHERE PT.NAME = 'WEEKLY';